# seq_len: 3
# stride: 1
steps: 100
sigma: 0.001
ma_w: 5

# model
# hidden_ndim: 128
hidden_nch: 2048
lmd_pe: 0.0
lmd_y: 1
# nlayers: 1
# nheads: 8
# dropout: 0.1

# optim
lr: 0.0001
lr_min: 0.000001
t_max: 60

# training
epochs: 300
batch_size: 32
num_workers: 8
