seq_len: 30
stride: 1
steps: 10
sigma: 0.0

# model
hidden_ndim: 64
nlayers: 6
nheads: 8
dropout: 0.1

# optim
lr: 0.0001
lr_min: 0.000001
t_max: 20

# training
epochs: 100
batch_size: 256
num_workers: 8
