seq_len: 3
stride: 1
steps: 1
sigma: 0.001

# model
hidden_ndim: 128
hidden_nch: 512
lmd_pe: 0.001
# nlayers: 1
# nheads: 8
# dropout: 0.1

# optim
lr: 0.001
lr_min: 0.00001
t_max: 30

# training
epochs: 150
batch_size: 512
num_workers: 8
