seq_len: 5
stride: 1
steps: 100
sigma: 0.001

# model
hidden_ndim: 256
nlayers: 1
nheads: 8
dropout: 0.1

# optim
lr: 0.0001
lr_min: 0.00001
t_max: 20

# training
epochs: 100
batch_size: 256
num_workers: 8
